### ISSUE TITLE
导出Excel匹配的英文列表是中文

### ISSUE THREAD

**Issue by HELLOMaDong** [Leo0618/I18NTool#1]

**Comment by Leo0618** [comment]
如果英文定义资源文件里面的字符串包含中文，也会提取出来作为需要翻译的内容，这时候英文列表里面显示的就是中文

**Comment by HELLOMaDong** [comment]
但是发现values-string的键对应值是中文导出表格所有的值都是中文 如果是英文则返回所有值都是英文 是按照文档步骤操作但不知道是不是我个人操作问题，还是很疑惑，不知道大佬可以做个有做操作步骤GIF放在作品下面吗？ 谢谢大佬的回复我再试试看。

**Comment by Leo0618** [comment]
可以添加钉钉好友，沟通一下，钉钉号： o3yfp2g
